version: '3.1'
services:
  mcserver:
    #image: supi1290/minecraft_server:gina
    build: gina/
    restart: always
    ports:
      - "25565:25565"
      - "25575:25575"
    environment:
      - "MC_GINA_GIT_REPO="
      - "MC_GINA_GIT_USER="
      - "MC_GINA_GIT_PASSWD="
      - "MC_GINA_INTERVAL=daily"
      - "MODPACK_URL=https://media.forgecdn.net/files/2919/140/supi_server_docker.zip"
      - "MODPACK_FILENAME=supi_server_docker.zip"
      - "SERVER_PROPERTY_ALLOW_FLIGHT=true"
      - "SERVER_PROPERTY_DIFFICULTY=2"
      - "SERVER_PROPERTY_ENABLE_RCON=true"
      - "SERVER_PROPERTY_LEVEL_SEED=8240262212944608719"
      - "SERVER_PROPERTY_LEVEL_TYPE=BIOMESOP"
      - "SERVER_PROPERTY_MAX_BUILD_HEIGHT=512"
      - "SERVER_PROPERTY_MAX_PLAYERS=40"
      - "SERVER_PROPERTY_MOTD=Supi's Adventure Modpack Server"
      - "SERVER_PROPERTY_RCON_PASSWORD="
      - "EULA=true"
      - "JAVA_XMS=4096M"
      - "JAVA_XMX=5120M"